server:
  port: 8070

spring:
  config:
    import: configserver:http://localhost:9090/
  cloud:
    config:
      enabled: true

# DataBase Configuration

  datasource:
    url: jdbc:mysql://localhost:3306/electronic_Employee?createDatabaseIfNotExist=true&useSSL=true
    # Uncomment one of the following lines based on your preference
    # url: jdbc:mysql://localhost:3306/electronic_store
    username: root
    password: root

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# For Exception
SERVICE:
  EMPLOYEE: "Employee not present in the DataBase as per Pratik"

# For config


  logging:
    level:
      org.springframework.cloud.config: DEBUG

